-- Drop existing tables

DROP TABLE IF EXISTS user_group_access_rights;
DROP TABLE IF EXISTS user_access_rights;
DROP TABLE IF EXISTS project;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS user_group;
DROP TABLE IF EXISTS access_right;
DROP TABLE IF EXISTS task;


CREATE TABLE IF NOT EXISTS user_group
(
    user_group_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_name      VARCHAR(255),
    parent_group_id BIGINT,
    FOREIGN KEY (parent_group_id) REFERENCES user_group (user_group_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS user
(
    user_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username             VARCHAR(20),
    email                VARCHAR(30),
    position             VARCHAR(30),
    direct_supervisor_id BIGINT,
    immediate_supervisor_id BIGINT,
    FOREIGN KEY (direct_supervisor_id) REFERENCES user (user_id) ON DELETE CASCADE,
    FOREIGN KEY (immediate_supervisor_id) REFERENCES user (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS task
(
    task_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_name      VARCHAR(20),
    description    TEXT,
    type           VARCHAR(20),
    status         VARCHAR(20),
    parent_task_id BIGINT,
    FOREIGN KEY (parent_task_id) REFERENCES task (task_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS project
(
    project_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_name      VARCHAR(255),
    parent_project_id BIGINT,
    FOREIGN KEY (parent_project_id) REFERENCES project (project_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS access_right
(
    access_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_right_id BIGINT,
    FOREIGN KEY (parent_right_id) REFERENCES access_right (access_id) ON DELETE CASCADE
);

CREATE TABLE user_group_access_rights
(
    user_group_access_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_group_id        BIGINT,
    access_right_id      BIGINT,
    FOREIGN KEY (user_group_id) REFERENCES user_group (user_group_id) ON DELETE CASCADE,
    FOREIGN KEY (access_right_id) REFERENCES access_right (access_id) ON DELETE CASCADE
);

CREATE TABLE user_access_rights
(
    user_access_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT,
    access_right_id  BIGINT,
    FOREIGN KEY (user_id) REFERENCES user (user_id) ON DELETE CASCADE,
    FOREIGN KEY (access_right_id) REFERENCES access_right (access_id) ON DELETE CASCADE
);
