spring:
  datasource:
    url: ${JDBC_URL:jdbc:postgresql://prod-db-host:5432/prod_db_name}
    driver-class-name: ${DRIVER_CLASS_NAME:org.postgresql.Driver}
    username: ${DB_USERNAME:prod_user}
    password: ${DB_PASSWORD:prod_password}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${HBM_DDL_AUTO:validate}
    properties:
      hibernate:
        dialect: ${HBM_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
  h2:
    console.enabled: false
server:
  port: 8816
