DROP TABLE IF EXISTS task;
DROP TABLE IF EXISTS project;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS user_group;


CREATE TABLE IF NOT EXISTS project
(
    project_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_name      VARCHAR(255),
    created_date      DATE,
    description       TEXT,
    parent_project_id BIGINT,
    FOREIGN KEY (parent_project_id) REFERENCES project (project_id),
    deleted           BOOLEAN
);

CREATE TABLE IF NOT EXISTS task
(
    task_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_name      VARCHAR(255),
    description    TEXT,
    created_date   DATE,
    project_id     BIGINT,
    parent_task_id BIGINT,
    FOREIGN KEY (parent_task_id) REFERENCES task (task_id),
    FOREIGN KEY (project_id) REFERENCES project (project_id)
);

CREATE TABLE IF NOT EXISTS user
(
    user_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name      VARCHAR(255),
    user_group     VARCHAR(255),
    login          VARCHAR(255),
    password       VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS user_group
(
    user_group_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_name      VARCHAR(255),
    parent_group_id BIGINT
);